# Krotka: Zbior elementow roznych typow danych, ktorych nie mozna zmienic. Ma dostep tylko do odczytu do kolekcji. Mozna to wykorzystac, gdy chcesz zabezpieczyc zestaw do zbierania danych i nie potrzebujesz zadnych modyfikacji.
Krotka = ("Przyklad1", 2, 3.14, "Przyklad1", ["a","b","c"],True)
print(Krotka)
print(Krotka[-1])
print(Krotka[1:3])
print(Krotka.index(2))
print("b" in Krotka)
print(["a","b","c"] in Krotka)
print(len(Krotka))
Krotka = tuple(("Przyklad1", 2, "Przyklad3"))
print(type(Krotka))
Krotka = ("Przyklad",)
print(type(Krotka))
Krotka = ("Przyklad")
print(type(Krotka))